version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  ruby: &ruby
    image: ideoruby
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  webpacker:
    <<: *ruby
    command: ./bin/webpack-dev-server
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    ports:
      - 3035:3035

  web:
    <<: *ruby
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - 3000:3000
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  postgresql-data:
